### ISSUE TITLE
restore old URLs

### ISSUE THREAD

**Issue by stranak** [ufal/perl-pmltq#16]
The old URLs (before the last big upgrade to `pmltq/#!/xyz`) were actually used in publications. Now they don't work, we broke the links.

Can we restore the old URL system, or add URL rewriting for the old URLs?

**Comment by m1ch4ls** [comment]
What links exactly doesn't work? The rewriting is there since day one, for example: https://lindat.mff.cuni.cz/services/pmltq/pdt30/ works for me.

**Comment by stranak** [comment]
> On 20 Sep 2015, at 11:59, Michal Sedlák <notifications@github.com> wrote:
> 
> What links exactly doesn't work? The rewriting is there since day one, for example: https://lindat.mff.cuni.cz/services/pmltq/pdt30/ works for me.
> 
> 
Marketa reported it to me, so maybe she has other examples, but I found this simple one: 
https://lindat.mff.cuni.cz/services/pmltq/pdt30/query

Pavel

**Comment by stranak** [comment]
Hi,

the HamledDT links with the following form seem not
https://lindat.mff.cuni.cz/services/pmltq/hamledt_dt_de/

However, I am not able to open even the page cited by Michal - in fact, only a blind page appears (but I am in a train with slow wifi now).

MArketa

===========================================
Marketa Lopatkova
Associate Professor
Institute of Formal and Applied Linguistics
Charles University in Prague

**Comment by dan-zeman** [comment]
The "_dt" in the URL is a typo, isn't it?
But I confirm that I see a blank page too, with or without the "_dt".

**Comment by m1ch4ls** [comment]
I am fiddling with it right now...

I'd like the https://lindat.mff.cuni.cz/services/pmltq/treebank-name/ be the permanent link
and https://lindat.mff.cuni.cz/services/pmltq/#!/whatever to be in application link

The '_dt' looks like a typo.

**Comment by m1ch4ls** [comment]
Should be fixed.
