### ISSUE TITLE
queries in Help invisible in Safari

### ISSUE THREAD

**Issue by stranak** [ufal/perl-pmltq#42]
… but actually only on the production machine. In the quest VM for LDC it works fine.

"Invisible" means zero height of `div.code-listing` with the query. 

![screen shot 2017-06-08 at 10 06 25](https://user-images.githubusercontent.com/371106/26918462-6d057f4c-4c32-11e7-8e53-7520206fd3dd.png)

**Comment by matyaskopp** [comment]
This is consequence of:
```
Error: Invalid regular expression: regular expression too large
```
Highlighting doesn't work for treex, pdt and derived schemas

duplicate https://github.com/ufal/perl-pmltq-web/issues/51
