### ISSUE TITLE
invalid link in documentation

### ISSUE THREAD

**Issue by matyaskopp** [ufal/perl-pmltq#52]
link to [Tiger Corpus 1.0](http://www.ims.uni-stuttgart.de/projekte/TIGER/TIGERCorpus/)  on https://ufal.mff.cuni.cz/pmltq/ does not work

**Comment by dan-zeman** [comment]
They have moved the page, now it is at http://www.ims.uni-stuttgart.de/forschung/ressourcen/korpora/tiger.html
