### ISSUE TITLE
documentation: Bug in example

### ISSUE THREAD

**Issue by matyaskopp** [ufal/perl-pmltq#62]
There should be nodetypes after relations: https://ufal.mff.cuni.cz/pmltqdoc/doc/pmltq_doc.html#idp52955584
![image](https://user-images.githubusercontent.com/5867995/108688437-3122ae80-74f8-11eb-8bcb-66b84b3ef740.png)

https://github.com/ufal/perl-pmltq/blob/f1e8e995cdeaa25b16caed54cc718c9f490f8896/doc/pmltq_doc.xml#L2470-L2475

**Comment by jmirovsky** [comment]
Fixed at the ufal.mff.cuni.cz server.
